<dt class="payment-method-fields">
    <fieldset>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="custom_field"><?php echo $this->__('Custom Field') ?></label>
                    <div class="input-box">
                        <input type="text" name="custom_field" value="" title="<?php echo $this->__('Custom Field') ?>" id="custom_field" /></div>
                    </div>
                </li>
            </ul>
        </fieldset>
    </dt>